#!/usr/bin/env python3
"""Byte-by-byte verification of the Rust `snapkv` crate against the REAL NVIDIA kvpress
`SnapKVPress` — the actual library, not the pure-Python re-implementations in this dir.

The unit tests (`src/tests.rs`) assert the Rust against two committed oracle fixtures
(`tests/fixtures/budget_grid.csv`, `select_fixture.txt`) generated by `snapkv_budget_ref.py` and
`snapkv_select_ref.py` (which composes pyramidkv's shared selection oracle with this budget). THIS
script closes the last link: it drives the installed `kvpress.SnapKVPress.compress` end to end and
confirms the REAL library reproduces those fixtures exactly, so `Rust == fixture == real kvpress`.

What it checks:
  [1] BUDGET   real SnapKVPress.compress keeps EXACTLY budget_grid.csv's count for every row
               (`int(k_len * (1 - cr))` — truncation), plus a random sweep vs the oracle. [byte-identical]
  [2] STAGE    real SnapKVPress.compress on the fixture's LCG attention returns EXACTLY the per-kv-head
               keep sets in select_fixture.txt — budget AND selection, end to end.      [byte-identical]
               A mismatch is diagnosed: an exact score tie at the top-k cut is the documented residual
               (torch.topk's tie order is implementation-defined), anything else is a bug.

Setup (the pyramidkv venv; Python >= 3.13 removed stdlib `pipes`, which kvpress's transitive dep
`fire` imports — a 2-line shim is injected below. kvpress 0.5.4 pins transformers<5.3):
    python3 -m venv --system-site-packages .venv           # reuse an existing CPU torch
    . .venv/bin/activate
    pip install "transformers>=4.56,<5.3" "kvpress==0.5.4"
    python verify_vs_kvpress.py                             # exit 0 iff all checks pass

Pinned reference: kvpress==0.5.4 (`ScorerPress.compress`: n_kept = int(k_len * (1 - cr));
`SnapKVPress.score`: mean over the window → avg_pool1d → GQA group-mean → window padded at max+1).
No CUDA required.
"""

import csv
import importlib.util
import os
import random
import shlex
import sys
import types

if "pipes" not in sys.modules:
    _p = types.ModuleType("pipes")
    _p.quote = shlex.quote
    sys.modules["pipes"] = _p

import torch  # noqa: E402
from kvpress import SnapKVPress  # noqa: E402  (the REAL reference)

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "..", "tests", "fixtures")
PYRAMIDKV_REF = os.path.join(HERE, "..", "..", "pyramidkv", "reference")


def _load(directory, name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(directory, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


budget_ref = _load(HERE, "snapkv_budget_ref")
select_ref = _load(PYRAMIDKV_REF, "pyramidkv_select_ref")  # the shared selection oracle (synth_attn)


class _Cfg:
    def __init__(self, n_q, n_kv):
        self.num_attention_heads = n_q
        self.num_key_value_heads = n_kv
        self.num_hidden_layers = 1


class _Mod:
    """Minimal stand-in for a decoder layer's self_attn module: only the attributes kvpress reads."""

    def __init__(self, n_q, n_kv, head_dim=8):
        self.config = _Cfg(n_q, n_kv)
        self.layer_idx = 0
        self.head_dim = head_dim


def real_compress_keep(attn_sum, n_kv, n_q, window, kernel, cr, dtype=torch.float64):
    """Drive the REAL `SnapKVPress.compress` and read back which positions it kept.

    `attn_sum[h][p]` is the engine's `TensorKind::PrefillAttention`: attention summed over the
    trailing `window` queries to prefix key `p`, per attention head. `score()` means over the window
    rows, so each of the `window` observation rows is set to `attn_sum/window`; the mean then equals
    `attn_sum/window`, matching the Rust `v * inv_window`. Keys are tagged with their position in
    lane 0, so the gathered keys reveal the kept set. Returns one ascending list per kv-head."""
    k_len = len(attn_sum[0])
    heavy = k_len - window
    attn = torch.zeros(1, n_q, k_len, k_len, dtype=dtype)
    for h in range(n_q):
        col = torch.tensor([attn_sum[h][p] / window for p in range(heavy)], dtype=dtype)
        attn[0, h, -window:, :heavy] = col.unsqueeze(0).expand(window, heavy)
    hd = 8
    keys = torch.zeros(1, n_kv, k_len, hd, dtype=dtype)
    keys[0, :, :, 0] = torch.arange(k_len, dtype=dtype)
    values = keys.clone()
    hs = torch.zeros(1, k_len, hd, dtype=dtype)  # only shape[1] (> window) is read
    press = SnapKVPress(compression_ratio=cr, window_size=window, kernel_size=kernel)
    k_out, _ = press.compress(_Mod(n_q, n_kv, hd), hs, keys, values, attn, {})
    return [sorted(k_out[0, h, :, 0].long().tolist()) for h in range(n_kv)]


def real_score(attn_sum, n_kv, n_q, window, kernel, dtype=torch.float64):
    """The REAL `SnapKVPress.score()` per kv-head (`[n_kv, k_len]`, window padded at max+1)."""
    k_len = len(attn_sum[0])
    heavy = k_len - window
    attn = torch.zeros(1, n_q, k_len, k_len, dtype=dtype)
    for h in range(n_q):
        col = torch.tensor([attn_sum[h][p] / window for p in range(heavy)], dtype=dtype)
        attn[0, h, -window:, :heavy] = col.unsqueeze(0).expand(window, heavy)
    keys = torch.zeros(1, n_kv, k_len, 8, dtype=dtype)
    hs = torch.zeros(1, k_len, 8, dtype=dtype)
    press = SnapKVPress(compression_ratio=0.5, window_size=window, kernel_size=kernel)
    return press.score(_Mod(n_q, n_kv), hs, keys, keys, attn, {})[0]


def real_kept_count(k_len, cr):
    """How many positions the REAL compress keeps for a `k_len`-long cache (window=kernel=1; the
    count does not depend on the scores). kvpress asserts q_len > window, so k_len >= 2."""
    attn = torch.zeros(1, 1, k_len, k_len, dtype=torch.float32)
    keys = torch.zeros(1, 1, k_len, 8, dtype=torch.float32)
    hs = torch.zeros(1, k_len, 8, dtype=torch.float32)
    press = SnapKVPress(compression_ratio=cr, window_size=1, kernel_size=1)
    k_out, _ = press.compress(_Mod(1, 1), hs, keys, keys, attn, {})
    return k_out.shape[2]


# ── [1] BUDGET ────────────────────────────────────────────────────────────────
def check_budget():
    rows = list(csv.DictReader(open(os.path.join(FIXTURES, "budget_grid.csv"))))
    bad = skipped = 0
    for r in rows:
        k_len = int(r["k_len"])
        if k_len < 2:
            skipped += 1  # kvpress asserts q_len > window_size (>= 1); the oracle still covers it
            continue
        got = real_kept_count(k_len, float(r["compression_ratio"]))
        bad += got != int(r["budget"])
    rng = random.Random(20260902)
    swept = swbad = 0
    for _ in range(3000):
        k_len = rng.choice([rng.randint(2, 64), rng.randint(2, 1024)])
        cr = rng.choice([1e-6, 0.5, 0.999999, rng.random()])
        swept += 1
        swbad += real_kept_count(k_len, cr) != budget_ref.snapkv_budget(k_len, cr)
    ok = bad == 0 and swbad == 0
    print(f"[1] BUDGET      : {len(rows) - skipped} grid rows ({skipped} skipped: q_len <= window) + "
          f"{swept} random | mismatches={bad + swbad} -> {'PASS (byte-identical)' if ok else 'FAIL'}")
    return ok


# ── [2] STAGE ─────────────────────────────────────────────────────────────────
def _parse_select(path):
    cases, cur = [], None
    for ln in open(path):
        t = ln.split()
        if t and t[0] == "CASE":
            cur = {"p": t[1:], "keep": []}
            cases.append(cur)
        elif t and t[0] == "KEEP":
            cur["keep"].append(list(map(int, t[1:])))
    return cases


def check_stage():
    cases = _parse_select(os.path.join(FIXTURES, "select_fixture.txt"))
    bad = ties = heads = 0
    for c in cases:
        n_kv, n_q, k_len, w, k = map(int, c["p"][:5])
        cr = float(c["p"][5])
        seed = int(c["p"][6])
        attn = select_ref.synth_attn(n_q, k_len, seed)
        real = real_compress_keep(attn, n_kv, n_q, w, k, cr)
        n_kept = budget_ref.snapkv_budget(k_len, cr)
        for h in range(n_kv):
            heads += 1
            if real[h] == c["keep"][h]:
                continue
            # Diagnose: same COUNT and every differing position tied at the cut = torch tie order
            # (the documented residual); anything else is a structural bug.
            sc = real_score(attn, n_kv, n_q, w, k)[h]
            diff = set(real[h]) ^ set(c["keep"][h])
            tie = (len(real[h]) == len(c["keep"][h]) == n_kept
                   and len({float(sc[p]) for p in diff}) == 1)
            ties += tie
            bad += not tie
            print(f"    case seed={seed} kv-head {h}: {'exact-tie residual' if tie else 'MISMATCH'} "
                  f"diff={sorted(diff)}")
    ok = bad == 0
    print(f"[2] STAGE       : {len(cases)} cases / {heads} kv-heads | mismatches={bad} "
          f"(exact-tie residuals={ties}) -> {'PASS (byte-identical)' if ok else 'FAIL'}")
    return ok


if __name__ == "__main__":
    torch.manual_seed(0)
    results = [check_budget(), check_stage()]
    print("RESULT:", "ALL BYTE-IDENTICAL CHECKS PASS ✓" if all(results) else "FAILURES ✗")
    sys.exit(0 if all(results) else 1)
