#!/usr/bin/env python3
"""Byte-by-byte verification of the Rust `pyramidkv` crate against the REAL NVIDIA kvpress
`PyramidKVPress` — the actual library, not the pure-Python re-implementations in this dir.

The unit tests (`src/tests.rs`) assert the Rust against two committed oracle fixtures
(`tests/fixtures/budget_grid.csv`, `select_fixture.txt`) that are generated by verbatim ports
of the kvpress arithmetic (`pyramidkv_budget_ref.py`, `pyramidkv_select_ref.py`). THIS script
closes the last link: it drives the installed `kvpress.PyramidKVPress` and confirms the REAL
library reproduces those fixtures exactly, so `Rust == fixture == real kvpress`. It also runs
the adversarial probes that characterise the three documented residuals.

What it checks (see README.md for the results table):
  [1] BUDGET      real PyramidKVPress.get_layer_budget == budget_grid.csv (whole grid) AND
                  == oracle over a large random+boundary sweep.                    [byte-identical]
  [2] SELECTION   real SnapKVPress.score()+torch.topk == select_fixture.txt.       [byte-identical]
  [3] ENGINE-FIX  real kvpress == the engine byte-identical test's hardcoded oracle
                  (budgets [24,19,13,8] + keep-sets in engine/src/stages/kv/prefill_keepset.rs).
  [4] ALGORITHM   on CONTINUOUS float attention, real score() == oracle score() to f64 noise
                  and 0 keep-set flips — proves no STRUCTURAL divergence.          [byte-identical]
  [5] RESIDUALS   informational: every integer-fixture divergence is an EXACT score tie (a
                  test-oracle artifact of the integer LCG, not a bug); the f16-vs-f32 keep-set
                  flip rate; the sub-window (n_kept<window) COUNT-only faithfulness.

Setup (Python >= 3.13 removed stdlib `pipes`, which kvpress's transitive dep `fire` imports; a
2-line shim is injected below. kvpress 0.5.4 pins transformers<5.3):
    python3 -m venv --system-site-packages .venv           # reuse an existing CPU torch
    . .venv/bin/activate
    pip install "transformers>=4.56,<5.3" "kvpress==0.5.4"  # torch>=2.3.1 already present
    python verify_vs_kvpress.py                             # exit 0 iff all byte-identical checks pass

Pinned reference: kvpress==0.5.4 (upstream git 6d965557; ports KVCache-Factory pyramidkv_utils.py
L197). No CUDA required — everything runs on CPU float64/float32/float16.
"""

import importlib.util
import os
import random
import shlex
import sys
import types

# Python 3.13+ dropped stdlib `pipes`; `fire` (pulled in by kvpress/__init__) still imports it.
# Inject a minimal shim BEFORE importing kvpress. Unrelated to PyramidKV correctness.
if "pipes" not in sys.modules:
    _p = types.ModuleType("pipes")
    _p.quote = shlex.quote
    sys.modules["pipes"] = _p

import torch  # noqa: E402
from kvpress import PyramidKVPress  # noqa: E402  (the REAL reference)

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "..", "tests", "fixtures")


def _load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


budget_ref = _load("pyramidkv_budget_ref")
select_ref = _load("pyramidkv_select_ref")


class _Cfg:
    def __init__(self, n_q, n_kv, nl):
        self.num_attention_heads = n_q
        self.num_key_value_heads = n_kv
        self.num_hidden_layers = nl


class _Mod:
    """Minimal stand-in for a decoder layer's self_attn module: only the attributes kvpress reads."""

    def __init__(self, nl, li, n_q=8, n_kv=8, head_dim=8):
        self.config = _Cfg(n_q, n_kv, nl)
        self.layer_idx = li
        self.head_dim = head_dim


def real_score(attn_sum, n_kv, n_q, window, kernel, dtype=torch.float64):
    """Feed per-q-head window-SUM attention through the REAL SnapKVPress.score().

    `attn_sum[h][p]` is the engine's `TensorKind::PrefillAttention`: attention summed over the
    trailing `window` queries to prefix key `p`, per attention head. score() does `.mean(dim=-2)`
    over the window rows, so we set each of the `window` observation rows to `attn_sum/window`;
    the mean then equals `attn_sum/window`, matching the Rust `v * inv_window`. Returns the
    per-kv-head score tensor `[n_kv, k_len]` (heavy scores + the max+1 padded window)."""
    k_len = len(attn_sum[0]) + window
    heavy = k_len - window
    attn = torch.zeros(1, n_q, k_len, k_len, dtype=dtype)
    for h in range(n_q):
        col = torch.tensor([attn_sum[h][p] / window for p in range(heavy)], dtype=dtype)
        attn[0, h, -window:, :heavy] = col.unsqueeze(0).expand(window, heavy)
    keys = torch.zeros(1, n_kv, k_len, 8, dtype=dtype)
    hs = torch.zeros(1, k_len, 8, dtype=dtype)  # only shape[1] (>window) is read
    press = PyramidKVPress(compression_ratio=0.5, window_size=window, kernel_size=kernel, beta=20)
    return press.score(_Mod(4, 0, n_q, n_kv), hs, keys, keys, attn, {})[0]


def real_keep(attn_sum, n_kv, n_q, window, kernel, n_kept, dtype=torch.float64):
    sc = real_score(attn_sum, n_kv, n_q, window, kernel, dtype)
    idx = sc.topk(n_kept, dim=-1).indices
    return [sorted(idx[kvh].tolist()) for kvh in range(n_kv)]


# ── [1] BUDGET ────────────────────────────────────────────────────────────────
def check_budget():
    import csv

    rows = list(csv.DictReader(open(os.path.join(FIXTURES, "budget_grid.csv"))))
    bad = 0
    for r in rows:
        press = PyramidKVPress(
            compression_ratio=float(r["compression_ratio"]),
            window_size=int(r["window_size"]),
            kernel_size=5,
            beta=int(r["beta"]),
        )
        got = press.get_layer_budget(_Mod(int(r["num_layers"]), int(r["layer_idx"])), int(r["q_len"]))
        bad += got != int(r["budget"])
    # random + boundary sweep vs the oracle (which the CSV is generated from)
    rng = random.Random(20240717)
    swept = swbad = 0
    for _ in range(60000):
        q = rng.choice([rng.randint(2, 64), rng.randint(2, 8192)])
        ws = rng.randint(1, max(1, q - 1))
        cr = rng.choice([1e-6, 0.5, 0.999999, rng.random()])
        beta = rng.choice([1, 2, 20, rng.randint(1, 64)])
        nl = rng.choice([2, 3, 16, 32, rng.randint(2, 80)])
        li = rng.randint(0, nl - 1)
        real = PyramidKVPress(compression_ratio=cr, window_size=ws, kernel_size=5, beta=beta).get_layer_budget(
            _Mod(nl, li), q
        )
        orc = budget_ref.get_layer_budget(
            budget_ref._Module(nl, li), q, compression_ratio=cr, window_size=ws, beta=beta
        )
        swept += 1
        swbad += real != orc
    ok = bad == 0 and swbad == 0
    print(f"[1] BUDGET      : {len(rows)} grid rows + {swept} random/boundary | mismatches={bad + swbad} "
          f"-> {'PASS (byte-identical)' if ok else 'FAIL'}")
    return ok


# ── [2] SELECTION ───────────────────────────────────────────────────────────────
def _parse_select(path):
    cases, cur = [], None
    for ln in open(path):
        t = ln.split()
        if t and t[0] == "CASE":
            cur = {"p": list(map(int, t[1:])), "keep": []}
            cases.append(cur)
        elif t and t[0] == "KEEP":
            cur["keep"].append(list(map(int, t[1:])))
    return cases


def check_selection():
    cases = _parse_select(os.path.join(FIXTURES, "select_fixture.txt"))
    bad = heads = 0
    for c in cases:
        n_kv, n_q, k_len, w, k, n_kept, seed = c["p"]
        heavy = k_len - w
        attn = [row[:heavy] for row in select_ref.synth_attn(n_q, k_len, seed)]
        got = real_keep(attn, n_kv, n_q, w, k, n_kept)
        for kvh in range(n_kv):
            heads += 1
            bad += got[kvh] != c["keep"][kvh]
    ok = bad == 0
    print(f"[2] SELECTION   : {len(cases)} cases / {heads} kv-heads | mismatches={bad} "
          f"-> {'PASS (byte-identical)' if ok else 'FAIL'}")
    return ok


# ── [3] ENGINE FIXTURE ──────────────────────────────────────────────────────────
def check_engine_fixture():
    # gen_engine_fixture.py params + the hardcoded oracle in engine/src/stages/kv/prefill_keepset.rs.
    NL, NKV, NQ, KL, W, K, BETA, SB = 4, 2, 4, 32, 4, 1, 2, 1000
    exp_budgets = [24, 19, 13, 8]
    exp_keep = [
        [[0, 1, 3, 5, 7, 8, 9, 11, 12, 13, 15, 16, 17, 18, 19, 20, 22, 25, 26, 27, 28, 29, 30, 31],
         [0, 1, 2, 4, 5, 7, 8, 10, 11, 14, 15, 16, 18, 19, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31]],
        [[1, 3, 4, 5, 7, 8, 9, 10, 11, 18, 19, 21, 22, 24, 25, 28, 29, 30, 31],
         [2, 5, 6, 7, 9, 10, 11, 12, 14, 16, 19, 21, 23, 24, 26, 28, 29, 30, 31]],
        [[0, 5, 7, 8, 11, 17, 19, 21, 25, 28, 29, 30, 31],
         [0, 4, 10, 12, 14, 16, 19, 20, 27, 28, 29, 30, 31]],
        [[3, 5, 16, 20, 28, 29, 30, 31],
         [0, 1, 9, 20, 28, 29, 30, 31]],
    ]
    bad = 0
    got_budgets = []
    for L in range(NL):
        press = PyramidKVPress(compression_ratio=0.5, window_size=W, kernel_size=K, beta=BETA)
        nk = press.get_layer_budget(_Mod(NL, L, NQ, NKV), KL)
        got_budgets.append(nk)
        bad += nk != exp_budgets[L]
        heavy = KL - W
        attn = [row[:heavy] for row in select_ref.synth_attn(NQ, KL, SB + L)]
        got = real_keep(attn, NKV, NQ, W, K, nk)
        for kvh in range(NKV):
            bad += got[kvh] != exp_keep[L][kvh]
    ok = bad == 0
    print(f"[3] ENGINE-FIX  : budgets {got_budgets} vs {exp_budgets} + all keep-sets | mismatches={bad} "
          f"-> {'PASS (byte-identical)' if ok else 'FAIL'}")
    return ok


# ── [4] ALGORITHM PARITY (continuous float → no structural divergence) ──────────
def check_algorithm_parity():
    rng = random.Random(4242)
    max_linf = 0.0
    n = benign = structural = 0
    for _ in range(1500):
        g = rng.choice([1, 2, 4])
        n_kv = rng.randint(1, 6)
        n_q = n_kv * g
        w = rng.randint(2, 20)
        k = rng.choice([1, 3, 5, 7])
        heavy = rng.randint(w + 1, 160)
        k_len = heavy + w
        n_kept = rng.randint(w, k_len - 1)
        attn = [[rng.uniform(0, 1e6) for _ in range(heavy)] for _ in range(n_q)]  # continuous
        sc = real_score(attn, n_kv, n_q, w, k)  # [n_kv, k_len]
        # oracle heavy scores, per kv-head
        per = [select_ref.avg_pool1d([attn[h][p] / w for p in range(heavy)], k, k // 2) for h in range(n_q)]
        osc = [[sum(per[kvh * g + gg][p] for gg in range(g)) / g for p in range(heavy)] for kvh in range(n_kv)]
        for kvh in range(n_kv):
            for p in range(heavy):
                max_linf = max(max_linf, abs(sc[kvh][p].item() - osc[kvh][p]))
        orc = select_ref.pyramidkv_keep_per_head(
            [[attn[h][p] for p in range(heavy)] + [0.0] * w for h in range(n_q)], n_kv, n_q, w, k, n_kept
        )
        real = [sorted(sc[kvh].topk(n_kept).indices.tolist()) for kvh in range(n_kv)]
        n += 1
        for kvh in range(n_kv):
            if orc[kvh] == real[kvh]:
                continue
            # A flip is BENIGN iff the swapped positions are a NEAR-TIE in the oracle scores
            # (|score gap| below 1e-6 ≫ the ~6e-11 torch-f64-vs-python-f64 rounding noise) — the
            # ranks are order-of-arithmetic-sensitive, not a structural divergence. A gap above
            # 1e-6 would be a real selection bug.
            so, sr = set(orc[kvh]), set(real[kvh])
            gap = max((osc[kvh][p] for p in (so - sr) if p < heavy), default=0.0) - min(
                (osc[kvh][p] for p in (sr - so) if p < heavy), default=0.0
            )
            if abs(gap) < 1e-6:
                benign += 1
            else:
                structural += 1
    ok = structural == 0 and max_linf < 1e-6
    print(f"[4] ALGORITHM   : {n} continuous-float configs | max|score diff|={max_linf:.2e} "
          f"near-tie flips={benign} structural flips={structural} "
          f"-> {'PASS (byte-identical, no structural divergence)' if ok else 'FAIL'}")
    return ok


# ── [5] RESIDUALS (informational) ───────────────────────────────────────────────
def report_residuals():
    rng = random.Random(20240717)
    # 5a: every integer-fixture divergence is an EXACT score tie (not a bug).
    checked = tie = nontie = 0
    for _ in range(4000):
        g = rng.choice([1, 1, 2, 4])
        n_kv = rng.randint(1, 8)
        n_q = n_kv * g
        w = rng.randint(2, 24)
        k = rng.choice([1, 3, 5, 7])
        heavy = rng.randint(w + 1, 200)
        k_len = heavy + w
        n_kept = rng.randint(w, k_len - 1)
        seed = rng.randint(1, 10**9)
        attn = select_ref.synth_attn(n_q, k_len, seed)
        orc = select_ref.pyramidkv_keep_per_head(attn, n_kv, n_q, w, k, n_kept)
        sc = real_score([row[:heavy] for row in attn], n_kv, n_q, w, k)
        real = [sorted(sc[kvh].topk(n_kept).indices.tolist()) for kvh in range(n_kv)]
        for kvh in range(n_kv):
            if orc[kvh] == real[kvh]:
                continue
            checked += 1
            so, sr = set(orc[kvh]), set(real[kvh])
            row = sc[kvh].tolist()
            vo = sorted(round(row[p], 9) for p in (so - sr))
            vr = sorted(round(row[p], 9) for p in (sr - so))
            tie += vo == vr
            nontie += vo != vr
    # 5b: f16 vs f32 keep-set flip rate on continuous float attention.
    flips = N = 0
    for _ in range(200):
        g = rng.choice([1, 2, 4])
        n_kv = rng.randint(1, 4)
        n_q = n_kv * g
        w = rng.randint(4, 16)
        heavy = rng.randint(60, 160)
        k_len = heavy + w
        n_kept = rng.randint(w + 5, k_len - 2)
        attn = [[rng.random() for _ in range(heavy)] for _ in range(n_q)]
        N += 1
        flips += real_keep(attn, n_kv, n_q, w, 5, n_kept, torch.float32) != real_keep(
            attn, n_kv, n_q, w, 5, n_kept, torch.float16
        )
    print(f"[5] RESIDUALS   : integer-fixture divergences: {checked} checked, {tie} EXACT ties, "
          f"{nontie} non-tie bugs (want 0)")
    print(f"                  f16-vs-f32 keep-set flip rate: {flips}/{N} ({100 * flips / N:.0f}%) "
          f"[finite-precision, boundary-only; f32 is exact]")
    print(f"                  sub-window n_kept<window: only the COUNT is faithful (kvpress torch.topk "
          f"tie order among the equal-scored window, not recency)")
    return nontie == 0


def main():
    print(f"kvpress reference: PyramidKVPress from {PyramidKVPress.get_layer_budget.__module__} "
          f"| torch {torch.__version__}")
    results = [
        check_budget(),
        check_selection(),
        check_engine_fixture(),
        check_algorithm_parity(),
    ]
    residual_ok = report_residuals()
    allok = all(results) and residual_ok
    print("=" * 78)
    print("RESULT:", "ALL BYTE-IDENTICAL CHECKS PASS ✓" if allok else "FAILURE ✗")
    return 0 if allok else 1


if __name__ == "__main__":
    sys.exit(main())
